import Link from 'next/link';
import { Card, PageHeader } from '@home-folder/ui';
import { ActionLink } from '../components/ActionLink';

const EFFECTIVE_DATE = 'July 16, 2026';

function Section({ heading, children }: { heading: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 8 }}>
      <h2 style={{ marginBottom: 8 }}>{heading}</h2>
      <div style={{ color: 'var(--text-primary)', display: 'grid', gap: 10 }}>{children}</div>
    </section>
  );
}

export default function PrivacyPolicyPage() {
  return (
    <>
      <PageHeader
        eyebrow={`Effective ${EFFECTIVE_DATE}`}
        title="Privacy Policy"
        description="How Our Home Folder, a product of JBran LLC, handles your information."
      >
        <ActionLink href="/terms" variant="secondary">Terms of Service</ActionLink>
      </PageHeader>

      <div style={{ display: 'grid', gap: 20, maxWidth: 820 }}>
        <Card>
          <p style={{ marginTop: 0 }}>
            This Privacy Policy explains how <strong>JBran LLC</strong> (“we,” “us,” or “our”) collects, uses, and
            protects information in connection with <strong>Our Home Folder</strong> (the “Service”) at
            ourhomefolder.com. By using the Service, you agree to this Policy.
          </p>
        </Card>

        <Card>
          <Section heading="1. Information We Collect">
            <p style={{ margin: 0 }}>We collect only what we need to provide the Service:</p>
            <ul style={{ margin: 0, paddingLeft: 20 }}>
              <li><strong>Account information</strong> — your email address and authentication details when you sign up.</li>
              <li>
                <strong>Content you provide</strong> — the home records you create: properties, rooms, utilities,
                appliances, tools, smart-home devices and automations, maintenance, repairs, issues, warranties,
                receipts, notes, and any documents or photos you upload.
              </li>
              <li><strong>Limited technical data</strong> — basic operational logs generated by our infrastructure providers to keep the Service running and secure.</li>
              <li><strong>Local storage</strong> — in signed-out “demo mode,” data stays in your browser’s local storage and is not sent to us.</li>
            </ul>
          </Section>

          <Section heading="2. Sensitive Information">
            <p style={{ margin: 0 }}>
              The Service is designed for you to store <em>references</em> to where secrets live (for example, a
              password-manager entry name), not the secrets themselves. Please do not enter passwords, Wi-Fi
              passwords, alarm or door codes, PINs, or similar secrets as plain text. Exports and shared reports are
              automatically screened to omit common secret phrasings, but you remain responsible for what you enter.
            </p>
          </Section>

          <Section heading="3. How We Use Information">
            <p style={{ margin: 0 }}>We use information to:</p>
            <ul style={{ margin: 0, paddingLeft: 20 }}>
              <li>provide, maintain, and secure the Service;</li>
              <li>authenticate you and enforce access controls;</li>
              <li>respond to support requests; and</li>
              <li>comply with legal obligations.</li>
            </ul>
            <p style={{ margin: 0 }}>We do not sell your personal information, and we do not use your home records for advertising.</p>
          </Section>

          <Section heading="4. How Your Data Is Stored & Secured">
            <p style={{ margin: 0 }}>
              Your data is stored using Supabase (managed PostgreSQL, authentication, and private file storage).
              Data is encrypted in transit and at rest by our infrastructure providers. Access is enforced by
              database Row-Level Security so that records tied to your property are accessible only to you and to
              people you explicitly share with. Uploaded files are kept in a private storage bucket and served
              through short-lived, access-controlled links — not public URLs.
            </p>
          </Section>

          <Section heading="5. Sharing & Disclosure">
            <p style={{ margin: 0 }}>We share information only:</p>
            <ul style={{ margin: 0, paddingLeft: 20 }}>
              <li><strong>at your direction</strong> — when you use the Service’s sharing or handover features, or download an export;</li>
              <li><strong>with service providers (sub-processors)</strong> — notably Supabase, which hosts the Service’s data on our behalf under its own security and privacy commitments; and</li>
              <li><strong>when required by law</strong> — to comply with legal process or protect rights, safety, and security.</li>
            </ul>
            <p style={{ margin: 0 }}>We do not sell or rent your personal information to third parties.</p>
          </Section>

          <Section heading="6. Data Retention">
            <p style={{ margin: 0 }}>
              We retain your information for as long as your account is active or as needed to provide the Service.
              When you delete a record or your account, we remove the associated data from active systems, except
              where limited retention is required by law. Backups are cycled on a rolling basis.
            </p>
          </Section>

          <Section heading="7. Your Rights & Choices">
            <p style={{ margin: 0 }}>
              You can access, correct, and export your information directly within the Service, and you can delete
              records or your entire account at any time from <Link href="/settings" style={{ color: 'var(--color-brass-deep)' }}>Account settings</Link>.
              Depending on where you live, you may have additional rights (such as under the GDPR or CCPA/CPRA),
              including the right to access, correct, delete, or restrict processing of your personal data. To
              exercise these rights, contact us using the details below.
            </p>
          </Section>

          <Section heading="8. Cookies & Local Storage">
            <p style={{ margin: 0 }}>
              The Service uses only the storage necessary to operate — an authentication session and, in demo mode,
              your browser’s local storage. We do not use third-party advertising or cross-site tracking cookies.
            </p>
          </Section>

          <Section heading="9. Children’s Privacy">
            <p style={{ margin: 0 }}>
              The Service is intended for adults and is not directed to children under 13 (or the minimum age in
              your jurisdiction). We do not knowingly collect personal information from children. If you believe a
              child has provided us information, contact us and we will delete it.
            </p>
          </Section>

          <Section heading="10. Changes to This Policy">
            <p style={{ margin: 0 }}>
              We may update this Policy from time to time. We will update the “Effective” date above and, for
              material changes, provide additional notice where appropriate.
            </p>
          </Section>

          <Section heading="11. Contact Us">
            <p style={{ margin: 0 }}>
              JBran LLC — Our Home Folder<br />
              Privacy inquiries: <a href="mailto:privacy@ourhomefolder.com" style={{ color: 'var(--color-brass-deep)' }}>privacy@ourhomefolder.com</a>
            </p>
          </Section>
        </Card>

        <Card>
          <p style={{ margin: 0, color: 'var(--text-muted)', fontSize: 14 }}>
            See also our <Link href="/terms" style={{ color: 'var(--color-brass-deep)' }}>Terms of Service</Link>.
          </p>
        </Card>
      </div>
    </>
  );
}
