-- Historical placeholder.
--
-- The original 001 migration was quarantined because it contained invalid RLS
-- policy SQL and overbroad legacy policies. The canonical schema starts in
-- 002_phase6a_foundation.sql. Hosted projects that already recorded this
-- migration should keep their migration history and apply later cleanup
-- migrations; fresh local resets should treat this file as intentionally empty.
